### ISSUE TITLE
Provide comparison to similar tools

### ISSUE THREAD

**Issue by pocc** [NicolaiSoeborg/ELF2deb#4]
How is this different from https://github.com/jordansissel/fpm? What advantages does it have over the competition (and what is that competition)?

**Comment by NicolaiSoeborg** [comment]
I didn't know about fpm, but for termshark you probably want to use that (if you want to package it for multiple distros).

Otherwise I think the advantage of this is simplicity (python, 1 dependency, only 7k in size), but thanks for the issues and ideas -- I will fix them now :smile:
